# Generated by Django 5.2.8 on 2025-12-11 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_seed_program_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='card_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='MembershipCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('membership', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card', to='crm.membership')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
