# Generated by Django 5.2.8 on 2025-12-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_membership_card_number_membershipcard'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stamp',
            constraint=models.UniqueConstraint(condition=models.Q(('pos_receipt_number__isnull', False)), fields=('pos_receipt_number',), name='unique_receipt_number_when_present'),
        ),
    ]
